### PR TITLE
Update setup

### PR DESCRIPTION
**Pull request by PaulLeCam**

### CODE REVIEW

**Review by oed — COMMENTED** [review]
Looks good. Are you planning on working on this? Would be good to test with js-did perhaps?

**Review by oed — APPROVED** [review]
Let's just disable the size test for now?

**Comment by PaulLeCam** [comment]
I wasn't planning on working on this further, mostly wanted to unblock Spencer on the circular dependencies issue with his PR, but I can help as needed.

About testing with js-did I think we should avoid bringing this dependency here, even as dev dependencies that causes issues when linking. I think the main integration test between this lib and js-did would be the Ceramic CI.
We should definitely add more unit tests though.

Regarding the size limit error, I think it might be failing because it's not setup in the master branch so it can't load data to make the diff but hopefully that should work for future PRs. Maybe we can try to merge it with this setup and remove it if needed?

**Comment by oed** [comment]
Nice, looks like CI passed on master 👍

**Pull request merged**
